name: README build
on:
  push:
    branches:
      - main
  schedule:
    - cron: '27 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Tokyo'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          git config --global user.name "$USERNAME"
          git config --global user.email "$EMAIL"
        env:
          USERNAME: ${{ secrets.USERNAME }}
          EMAIL: ${{ secrets.EMAIL }}
      - run: node main.js
        env:
          OPEN_WEATHER_MAP_KEY: ${{ secrets.OPEN_WEATHER_MAP_KEY }}
          LON: ${{ secrets.LON }}
          LAT: ${{ secrets.LAT }}
      - run: |
          git add README.md
          git add LICENSE
          git commit --amend --date="$(date -R)" -m "Updated at $(date -R)"
          git push -f origin main
